<?php
/**
 * Created by PhpStorm.
 * User: utente pc
 * Date: 17/08/2017
 * Time: 17.52
 */

    include "./class/Login.php";
    require_once "http_control.php";
    require_once "db_request.php";
    require_once "Exceptions.php";

/*header('Content-Type: application/json;charset=UTF-8');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: DELETE, HEAD, GET, OPTIONS, POST, PUT');
header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');
header('Access-Control-Max-Age: 1728000');*/

/*define ("db_user", "root");
define ("db_host", "localhost");
define ("db_port", 3306);
define ("db_name", "sito_web");
define ("db_pwd", "");*/

    $server_response = ['username_err'=>'err_1',
        'db_conn_err'=>'err_2',
        'pwd_err'=>'err_3',
        'db_err'=>'err_4',
        'param_err'=>'err_5',
        'empty_field'=>'err_6',
        'ok_login'=>'ok'
        ];

    /* begin the session */
    session_start();

    /* redirect the response on https if not */
   // https_check();

    /* suppress all the warning generated by the script */
    error_reporting(E_ERROR | E_PARSE);

    switch ($_SERVER["REQUEST_METHOD"]) {
        case "GET":
            if (isset($_GET["email"]) && isset($_GET["password"]))
                $login_info = new Login($_GET["email"], $_GET["password"]);
            else
                die($server_response['param_err']);
            break;

        case "POST":
            if (isset($_POST["email"]) && isset($_POST["password"]))
                $login_info = new Login($_POST["email"], $_POST["password"]);
            else
                die($server_response['param_err']);
            break;

        default:
            die($server_response['param_err']);
            break;
    }


    if (!$login_info->checkLoginDataValidity())
        die($server_response["empty_field"]);

    try {
        /* check the user info inside the DB */
        $mysql_conn = new mysqli(db_host, db_user, db_pwd, db_name);

        if ($mysql_conn->connect_errno) {
            error_log("DB error: ".$mysql_conn->connect_error,3,"/error_log.txt");
            die($server_response['db_conn_err']);
        }
//
//        /* create the sql query string */
//        $escaped_string = $mysql_conn->real_escape_string($login_info->getUsername());
//        $query_string = "SELECT user.password, user.salt FROM user WHERE username = '$escaped_string'";
//
//        if ($query_result = $mysql_conn->query($query_string)) {
//
//            $result_array = $query_result->fetch_array(MYSQLI_BOTH);
//            $other_result = $query_result->fetch_array(MYSQLI_BOTH);
//
//            // this type of error is returned if the database return more than one row
//             /* if (!empty($other_result)) {
//              throw new Exception("database error");
//            }*/
//
//            if (empty($result_array)) {
//                $response = $server_response['login_err'];
//            } else {
//                // the generation of the hash can throw an Exception
//                if ($login_info->checkLoginPassword($result_array["salt"], $result_array["password"])) {
//                    session_setup($login_info->getUsername());
//                    $response = $server_response['ok_login'];
//                } else
//                    $response = $server_response['pwd_err'];
//            }
//
//        } else
//            $response = $server_response['db_err'];

        $result = $login_info->checkLoginInfo($mysql_conn);

        if ($result)
            $response = $server_response["ok_login"];
         else
            $response = $server_response["pwd_err"];

        // close the script and return the parameter to the client
        $mysql_conn->close();
        die($response);

    } catch(DatabaseException $de) {
        $mysql_conn->close();
        die($server_response["db_err"]);
    } catch(RecordNotFoundException $re) {
        $mysql_conn->close();
        die($server_response["username_err"]);
    }

