<?php
/**
 * Created by PhpStorm.
 * User: utente pc
 * Date: 17/08/2017
 * Time: 17.52
 */

    include "login.php";
    include "http_control.php";
    include "db_request.php";

/*header('Content-Type: application/json;charset=UTF-8');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: DELETE, HEAD, GET, OPTIONS, POST, PUT');
header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');
header('Access-Control-Max-Age: 1728000');*/

/*define ("db_user", "root");
define ("db_host", "localhost");
define ("db_port", 3306);
define ("db_name", "sito_web");
define ("db_pwd", "");*/

    $server_response = array('login_err'=>'err_1',
        'db_conn_err'=>'err_2',
        'pwd_err'=>'err_3',
        'db_err'=>'err_4',
        'param_err'=>'err_5',
        'ok_login'=>'ok'
        );

    /* begin the session */
    session_start();

    /* redirect the response on https if not */
    https_check();

    /* suppress all the warning generated by the script */
    error_reporting(E_ERROR | E_PARSE);

    try {
        switch ($_SERVER["REQUEST_METHOD"]) {
            case "GET":
                if (isset($_GET["email"]) && isset($_GET["pwd"])) {
                    $login_info = new login($_GET["email"], $_GET["pwd"]);
                }
                else
                    throw new Exception("Parameter are not complete", 1);
                break;

            case "POST":
                if (isset($_POST["email"]) && isset($_POST["pwd"]))
                    $login_info = new login($_POST["email"], $_POST["pwd"]);
                else
                    throw new Exception("Parameter are not complete", 1);
                break;

            default:
                break;
        }
        $login_info->check_login();
    } catch (Exception $e) {
        die($server_response['param_err']);
    }
    try {
        /* check the user info inside the DB */
        $mysql_conn = new mysqli(db_host, db_user, db_pwd, db_name);

        if ($mysql_conn->connect_errno) {
            error_log("DB error: ".$mysql_conn->connect_error,3,"/error_log.txt");
            die($server_response['db_conn_err']);
        }

        /* create the sql query string */
        $escaped_string = $mysql_conn->real_escape_string($login_info->getUsername());
        $query_string = "SELECT web_user.password, web_user.salt FROM web_user WHERE username = '$escaped_string'";

        if ($query_result = $mysql_conn->query($query_string)) {

            $result_array = $query_result->fetch_array(MYSQLI_BOTH);
            $other_result = $query_result->fetch_array(MYSQLI_BOTH);

            // this type of error is returned if the database return more than one row
             /* if (!empty($other_result)) {
              throw new Exception("database error");
            }*/

            if (empty($result_array)) {
                $response = $server_response['login_err'];
            } else {
                // the generation of the hash can throw an Exception
                if ($result_array["password"] == $login_info->hash_pwd($result_array["salt"])) {
                    session_setup($login_info->getUsername());
                    $response = $server_response['ok_login'];
                } else {
                    $response = $server_response['pwd_err'];
                }
            }

        } else {
            $response = $server_response['db_err'];
        }

        // close the script and return the parameter to the client
        $mysql_conn->close();
        die($response);
    } catch (Exception $e) {
        $mysql_conn->close();
        die($server_response["param_err"]);
    }

