<?php
/**
 * Created by PhpStorm.
 * User: utente pc
 * Date: 17/08/2017
 * Time: 17.52
 */

    /* php script to check the login info sent by the client */
    include "./class/Registration.php";
    include "http_control.php";
    require_once "db_request.php";
    require_once "Exceptions.php";

    header('Access-Control-Allow-Origin: *');

    $server_response = array('db_err'=>'err_1',
                            'user_exits'=>'err_2',
                            'param_err'=>'err_3',
                            'email_error'=>'err_4',
                            'empty_param'=>'err_5',
                            'ok'=>'ok'
    );

    /* begin session */
    session_start();

    /* redirect the client to the https protocol if not */
   // https_check();

    /* suppress all the waring generated by the script */
    error_reporting(E_ERROR | E_PARSE);



    switch ($_SERVER["REQUEST_METHOD"]) {
        case "GET":
            if (isset($_GET["email"]) && isset($_GET["first-password"]))
                $registration = new Registration( $_GET["email"], $_GET["first-password"]);
            else
                die($server_response['param_err']);
            break;

        case "POST":
            if (isset($_POST["email"]) && isset($_POST["first-password"]))
                $registration = new Registration($_POST["email"], $_POST["first-password"]);
            else
                die($server_response['param_err']);
            break;

        default:
            die($server_response['param_err']);
            break;
    }

    // create a new connection
    $mysql_conn =  new mysqli(db_host, db_user, db_pwd, db_name);

    if ($mysql_conn->connect_errno) {
        error_log("DB error: ".$mysql_conn->connect_error,3,"/error_log.txt");
        $mysql_conn->close();
        die($server_response['db_err']);
    }

    if (!$registration->checkRegistrationData())
        die($server_response["empty_param"]);

    try {

        $mysql_conn->begin_transaction();

        if (!$registration->checkUserIntoDatabase($mysql_conn)) {
            die($server_response["user_exits"]);
        }

        if (!$registration->registerUser($mysql_conn)) {
            die($server_response["email_error"]);
        }

        $mysql_conn->commit();

    } catch(DatabaseException $de) {
        $mysql_conn->rollback();
        $mysql_conn->close();
        die($server_response["db_err"]);
    } catch(Exception $e) {
        // TODO MIGLIORARE QUESTA ECCEZION
        $mysql_conn->rollback();
        $mysql_conn->close();
        die($server_response["db_err"]);
    }


    // setup the session
    session_setup($registration->getUsername());
    die($server_response["ok"]);


//    /* sanitize the data received from the login page */
//    $name = $mysql_conn->real_escape_string($reg_info->getName());
//    $username = $mysql_conn->real_escape_string($reg_info->getUsername());
//
//    /* define the string to query the database */
//    $username_query = "SELECT web_user.username FROM web_user WHERE web_user.username = '$username'";
//    $user_result = $mysql_conn->query($username_query);
//
//    if (!empty($user_result->fetch_array())) {
//        $mysql_conn->close();
//        die($server_response['user_exits']);
//    }
//
//    /* generate new salt */
//    $salt = uniqid(mt_rand(), true);
//
//    /*generate Password and the salt to be persisted in the database */
//    $password = $mysql_conn->real_escape_string($reg_info->hashPassword($salt));
//    $persisted_salt = $mysql_conn->real_escape_string((string) $salt);
//
//    $insert_query = "INSERT INTO web_user(username, name, Password, salt) "
//        . "VALUES ('$username',P$passwordassword, '$persisted_salt', '$name')";
//
//    if ($mysql_conn->query($insert_query)) {
//        session_setup($reg_info->getUsername());
//        $response = $server_response["ok"];
//    } else {
//        $response = $server_response["db_err"];
//    }
//
//    $mysql_conn->close();
//    die($response);


