<?php
/**
 * Created by PhpStorm.
 * User: utente pc
 * Date: 25/06/2018
 * Time: 17.23
 */

require_once "Exceptions.php";

class RouteDAO {

    private $connection;

    public function __construct($connection) {
        $this->connection;
    }

    public function createRoute($departure_address, $arrival_address, $booked_seats) {
        $query1 = "INSERT INTO route('$departure_address', '$arrival_address', '$booked_seats') "
                    ."VALUES (departure_adddress, arrival_address, booked_seats)";

        if ($query_result = $this->connection->query($query1)) {
            // return the autogenerated id
            $route_id = $query_result->insert_id;
            $query_result->close();
            return $route_id;
        } else {
            throw new DatabaseException("impossible to insert a new route, database error");
        }
    }

    public function readFirstRoute() {
        // TODO da ricontrollare
        $query1 = "SELECT * FROM route ORDER BY route_id LIMIT 1";

        if ($query_result = $this->connection->query()) {

            $departure_address = $query_result->array_fetch(MYSQLI_ASSOC)["departure_address"];
            $query_result->close();
            return $departure_address;
        } else {
            throw new DatabaseException("impossible to read a route, database error");
        }
    }

    public function readLastRoute() {
        // TODO da ricontrollare
        $query1 = "SELECT * FROM route ORDER BY route_id DESC LIMIT 1";

        if ($query_result = $this->connection->query()) {

            $arrival_address = $query_result->array_fetch(MYSQLI_ASSOC)["departure_address"];
            $query_result->close();
            return $arrival_address;
        } else {
            throw new DatabaseException("impossible to read a route, database error");
        }
    }

    public function  readRoute2($address) {
        $query1 = "SELECT route_id, departure_address, arrival_address, booked_seats FROM route WHERE '$address' < LOWER(departure_address) AND '$address' > LOWER(arrival_address)";

        if ($query_result = $this->connection->query($query1)) {
            if ($query_result->num_rows() == 0) {
                $query_result->close();
                throw new RecordNotFoundException();
            }

            // fetch the data from the database and then create a new object that wrap the information
            $data = $query_result->fetch_array(MYSQLI_ASSOC);
            $new_route = new Route($data["route_id"], $data["departure_address"], $data["arrival_address"], $data["booked_seats"]);
            $query_result->close();

            // return selected route
            return $new_route;
        } else {
            throw new DatabaseException("impossible to execute the route read, database error");
        }
    }

    public function readRoute($route_id) {
        $query1 = "SELECT route_id, departure_address, arrival_address, booked_seats FROM route WHERE (route_id = '$route_id')";

        if ($query_result = $this->connection->query($query1)) {
            if ($query_result->num_rows() == 0) {
                $query_result->close();
                throw new RecordNotFoundException();
            }

            // fetch the data from the database and then create a new object that wrap the information
            $data = $query_result->fetch_array(MYSQLI_ASSOC);
            $new_route = new Route($data["route_id"], $data["departure_address"], $data["arrival_address"], $data["booked_seats"]);
            $query_result->close();

            // return selected route
            return $new_route;
        } else {
            throw new DatabaseException("impossible to execute the route read, database error");
        }
    }

    public function updateRoute2($address) {
        $query1 = "UPDATE route SET arrival_address = '$address' WHERE '$address' < LOWER(departure_address) AND '$address' > LOWER(arrival_address)";
        //$query2 = "UPDATE route(arrival_address) VALUES '$address2' WHERE '$address1' < LOWER(departure_address) AND '$address1' > LOWER(arrival_address)";

//        if ($is_start_adddress) {
//            $query_e = $query1;
//        } else {
//            $query_e = $query2;
//        }

        if (!$result_query = $this->connection->query($query1)) {
            throw new DatabaseException("impossible to eexcute the update in route table, database error");
        }

    }

    public function updateRoute($departure_route, $arrival_route, $seats_num) {
        $query1 = "UPDATE route SET booked_seats = booked_seats + '$seats_num' "
                    ."WHERE ('$departure_route' <= LOWER(departure_address) AND '$departure_route' > LOWER(arrival_address)) "
                    ."OR ('$departure_route' > LOWER(departure_address)) "
                    ."OR ('$arrival_route' < LOWER(departure_address) AND '$arrival_route' <= LOWER(arrival_address))";

        if ($query_result = $this->connection->query($query1)) {
            $query_result->close();
            throw new DatabaseException("impossible to update the records, database error");
        }

        $route_id_array = new ArrayObject();

        while ($row = $query_result->fetch_array()) {
            $route_id_array->append($row["route_id"]);
        }

        $query_result->close();
        return $route_id_array;
    }

    public function deleteRoute() {

    }

    public function queryRoute($departure_route, $arrival_route) {
        $query1 = "SELECT route.route_id, route.departure_address, route.arrival_address, route.booked_seats FROM route "
                    ."WHERE ('$departure_route' <= LOWER(departure_address) AND '$departure_route' > LOWER(arrival_address)) "
                    ."OR ('$departure_route' > LOWER(departure_address)) "
                    ."OR ('$arrival_route' < LOWER(departure_address) AND '$arrival_route' <= LOWER(arrival_address)) FOR UPDATE";

        if ($query_result = $this->connection->query($query1)) {

            // populate the array with the value returned by the database
            $booked_seats_array = new ArrayObject();

            if ($query_result->num_rows == 0) {
                return $booked_seats_array;
            }

            while ($row = $query_result->fetch_array(MYSQLI_ASSOC)) {
                $booked_seats_array->append($row["booked_seats"]);
            }

            return $booked_seats_array;

        } else {
            throw new DatabaseExpcetion("impossible to execute the query, database error");
        }

    }

}